# prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.appReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.appImage }}:{{ .Values.appVersion }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
          {{- range .Values.containerEnvVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          livenessProbe:
            {{- if eq .Values.probeType "httpGet" }}
            httpGet:
              path: {{ .Values.probePath }}
              port: {{ .Values.containerPort }}
            {{- else }}
            grpc:
              port: {{ .Values.containerPort }}
            {{- end }}
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            {{- if eq .Values.probeType "httpGet" }}
            httpGet:
              path: {{ .Values.probePath }}
              port: {{ .Values.containerPort }}
            {{- else }}
            grpc:
              port: {{ .Values.containerPort }}
            {{- end }}
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}


